# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  rouge
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: Justin's Blog
description: Frontend
keywords: JS,React,Node
feed: /atom.xml
favicon: /images/shortcut.jpg

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 关于我
    url: /about.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: Justin
    email: jzstxdy@gamil.com
    imageLink: /images/avator.jpg
    simpleIntro: 不积跬步，无以至千里。
    detailIntro:
      <p>西安程序员</p>
      <p>前端开发</p>
      <p>不断学习中...</p>

#Links
customLinks:
  - item:
    - text: Jekyll
      url: http://jekyllrb.com
    message: Friends    

